version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/Backend" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Frontend" # Location of package manifests
    schedule:
      interval: "daily"
